name: Build LaTeX document
on: [push]
permissions:
  contents: read
  pages: write
  id-token: write

jobs:

  build:

    runs-on:
      labels: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3

      - name: Prepare author variables
        run: |
          echo '\renewcommand\authorphone{'"${{ vars.AUTHOR_PHONE }}"'}' >> variables.tex
          cat variables.tex

      - name: Add fonts
        run: |
          wget https://github.com/theleagueof/raleway/releases/download/4.101/Raleway-4.101.zip
          unzip Raleway-4.101.zip
          mkdir -p ~/.local/share/fonts
          cp -r ./Raleway-4.101/static/TTF/* ~/.local/share/fonts/
          cp -r ./Raleway-4.101/static/TTF/Raleway-SemiBold.ttf ~/.local/share/fonts/Raleway-Semibold.ttf
          fc-cache -rv

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: |
            podimo.tex

      - name: PrepForDeploy
        run: |
          sudo chown runner:docker podimo.pdf
          mv podimo.pdf rolandas.griskevicius.podimo.pdf
          mkdir cv
          cp rolandas.griskevicius.podimo.pdf cv/

      - name: Debug0
        run: |
          ls -la
          ls -la cv/*

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'cv'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4


